### ISSUE TITLE
stake-set-lockup doesn't display custodian key

### ISSUE THREAD

**Issue by garious** [solana-labs/ledger-app-solana#119]
#### Problem

`solana stake-set-lockup` shows an authority of `111111111111111`. At a glance, I'd guess it's trying to display a stake authority instead of the custodian.

Also, it shows the unix timestamp integer for `--lockup-date` instead of parsing the RFC3339 DateTime.

#### Solution

Fix the first issue for sure.  The second would be a nice bonus, but not a big deal to leave that one out.

**Comment by t-nelson** [comment]
Note to self: https://github.com/chansen/c-timestamp/blob/master/timestamp_format.c

**Comment by t-nelson** [comment]
@garious Mind pasting CLI args for STR?  I get expected output from the libsol test.  The stake authority isn't passed with `StakeInstruction::SetLockup`.

**Comment by t-nelson** [comment]
n/m I see the issue

**Comment by garious** [comment]
This was fixed by @t-nelson
