### ISSUE TITLE
Allow blind signing

### ISSUE THREAD

**Issue by pashinov** [solana-labs/ledger-app-solana#146]
Hello! I'd like to sign a batch of transactions with ledger and it will be very annoyed approving one by one (about 100 transaction). Is it a bad way to sign transaction blindy? What reason did you disable this feature and is it posiible to enable it?

**Comment by t-nelson** [comment]
Signing a transaction without verifying its contents on the device totally defeats the purpose.  If you need to sign a bunch of stuff blindly, send the required funds from the ledger to an temporary wallet and do it there.

this will not be implemented

**Comment by pashinov** [comment]
Thanks for reply, @t-nelson! I understood. Unfortunately this transactions don't related to funds. We are going to connect Solana to our crosschain bridge and when transfer a customer to unlock funds in Solana should send to sol program a butch of verified signatures. It about 100 signatures with public keys and some additional info. I think I can fit all this data in 10 transactions but I'd like to our users with ledger wallets make a single action when use our bridge and there is no idea how it can be implemented in Solana side.
