### ISSUE TITLE
Hashes so long, may be ignored

### ISSUE THREAD

**Issue by garious** [solana-labs/ledger-app-solana#16]
#### Problem

Public keys take 3 screens to display

#### Proposed solution

Offer a setting to show just the first and last characters. i.e.`CXsF3x1...jjXyqb7`

With this setting, the assumption is that the host machine is *not* compromised, but that the user wants to sanity-check their own transaction before signing it.

**Comment by CriesofCarrots** [comment]
Closed by #20
