### ISSUE TITLE
Ledger JS library incompatibilities

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/ledger-app-solana#86]
#### Problem

The app seems to be incompatible with the JS library maintained by Ledger.  As reported by Florian at Staking Facilities:
> Ok, so I am trying the interaction with the getPubkey function. I added a println() to the ledger.rs write function to see the inputs. They Match completly with mine. An example output would be this: `Command: 2, P1: 0, P2:0, data: [2, 128, 0, 0, 44, 128, 0, 1, 245], data_len: 9`
>
> In Javascript, I use the official Transport library by ledger and do the following:
> ```
> return this.transport
>       .send(APDU_CLA, INS.GET_PUBKEY, P1_NON_CONFIRM, 0, bip44Path, [0x9000, 0x6a80])
> ```
> 
> Where those variables result in:
> 
> `cla: 224 INS: 2 p1: 0 p2: 0 data: Uint8Array(9) [2, 128, 0, 0, 44, 128, 0, 1, 245] data_len: Uint8Array(9) [2, 128, 0, 0, 44, 128, 0, 1, 245]`
> 
> And while this returns a publicKey in the solana rust implementation, it returns an error of Invalid Data (0x6a80) in js

#### Suggested Solution

At first glance, my suspicions lie with one of the following changes.  Still need to triage and investigate.

- Data length representation from `u8` to `u16`: https://github.com/solana-labs/ledger-app-solana/commit/cf768577ac7e1c348c813be516b1afb68714740f#diff-803c5170888b8642f2a97e5e9423d399R46
- Adjustment of meaning for `P1` and `P2` vars: https://github.com/solana-labs/ledger-app-solana/commit/90d067f5374bb05be203b113c4c0d5028c6625e2#diff-fbbc564748ecd06c32f525a90464db8cL10

cc/ @garious @CriesofCarrots @fkbenjamin

**Comment by CriesofCarrots** [comment]
Good instincts, @t-nelson , it looks to be the data length representation: https://github.com/LedgerHQ/ledgerjs/blob/c91dd12aa334220660691b74c78c407605d0ae44/packages/hw-transport/src/Transport.js#L205

That js method also limits the data length to 256 bytes, so it could fail to send messages our rust implementation would send.

Possible solutions I see:
- Rework the rust implementation to mirror the js method. This will require changes in the ledger-app-solana, so now is the time, if we're going to go that direction.
- Write a solana-specific js send method that casts data.length as a 2 bytes and uses this lower-level Transport method: https://github.com/LedgerHQ/ledgerjs/blob/c91dd12aa334220660691b74c78c407605d0ae44/packages/hw-transport/src/Transport.js#L114

**Comment by t-nelson** [comment]
@CriesofCarrots Excellent!  Thanks for confirmation! :pray:

Presumably, changing our app will be the lower barrier-to entry solution.  I'll look into it once I get through with what I'm working on now.

**Comment by garious** [comment]
If changing our app, consider adding a new instruction, such that we can maintain compatibility as either the CLI or Ledger app is upgraded.

**Comment by t-nelson** [comment]
@garious You don't suppose the current release is beta enough to toss?  Version check rust-side and puke a "please update" message

**Comment by garious** [comment]
Current release is in the wild and backing lots of SOL.

**Comment by t-nelson** [comment]
Fair point!  For my own curiosity, do we expect resistance to upgrades?  I'm unaware of any sentiment one way or the other

**Comment by garious** [comment]
I would expect resistance to upgrading, yes. When it comes to hardware wallets, I'd generally expect, "if it aint broke, don't fix it". Even though we understand why upgrades are safe, does the user? And even when safe, the user probably doesn't want to risk being locked out of their wallet because of some incompatibility with the client that drives it.

**Comment by t-nelson** [comment]
:+1: 

I don't see any precedent for going low-level with `Transport.exchange()` in the rest of the library.  We can cross that bridge with upstream when we get there.  If they nix we'll probably be looking at mandatory FW upgrade for using the Ledger Live wallet features

**Comment by fkbenjamin** [comment]
Just adding my opinion here: 
I agree that the current version is backing a lot of SOL (mine included), however I think that changing the app right now is the preferable solution looking at it long term.
I think it is better to make people upgrade now (who doesn't want to upgrade right now can still use the current cli version to interact with his ledger). 
The number of people using the ledger and being resistant to an upgrade will only increase from now on. Being compatible with the default libraries from ledger will be worth a lot once devs start building on it.
